name: deploy-dev
run-name: ${{ github.actor }} is deploying 🚀
on: [push]
jobs:
  deploy:
    # Runs on OS 
    runs-on: ubuntu-latest
    # setup-node version
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    # Steps in this job
    steps:
      # Setup deployment environment
      - name: Setup deployment environment
        run: echo " Deployment Started... "
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Serverless Framework
        run: npm install -g serverless
      # Checkout the repo to the runner
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy to SLS to AWS
        run: sls deploy --region ${{ secrets.AWS_REGION }} --stage ${{ github.ref_name }}


