name: deploy-dev
run-name: ${{ github.actor }} is deploying 🚀
on: [push]
jobs:
  deploy:
    # Runs on OS 
    runs-on: ubuntu-latest
    # setup-node version (Note : deploys for all three versions not good)
    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x, 20.x]
    # Steps in this job
    steps:
      # Setup deployment environment
      - name: Setup deployment environment
        uses: actions/setup-node@v3
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 18.x
      - name: Setup AWS credentials
        # uses: aws-actions/setup-sam@v1
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Serverless Framework
        run: npm install -g serverless
      # Checkout the repo to the runner
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy to SLS to AWS
        run: sls deploy --region ${{ secrets.AWS_REGION }} --stage ${{ github.ref_name }}


